/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to:
 * https://docs.gradle.org/8.10.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs, which are subject to change.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()  // Resolve plugins from the Gradle Plugin Portal.
        mavenCentral()
    }
}

plugins {
    // Use foojay-resolver to automatically manage and download JDKs.
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()  // Primary repository for resolving project dependencies.
    }
}

rootProject.name = "bptree-library"  // Set the root project name.

// Include sub-projects if any (for example, 'lib' in a multi-project setup).
include("lib")
